import fs from 'fs/promises';
import path from 'path';
import os from 'os';
import { ProjectFile } from '../models/ProjectFile.js';
import { buildS3Key, uploadFile } from './s3.js';
import { getObjectStream } from './s3.js';
import { pipeline } from 'stream/promises';
import { createWriteStream } from 'fs';
import { skillMeta } from './skillRegistry.js';
import { exportDxfFromScript, uploadSidecarIfExists } from './cadExportService.js';

export function wantsSendCutSend(userMessage = '') {
  return /\b(sendcutsend|send\s*cut\s*send|laser\s*cut\s*order|sheet\s*metal\s*quote)\b/i.test(userMessage);
}

async function tryExportDxfForStep({ userId, projectId, stepDoc, workDir, onProgress }) {
  const base = path.basename(stepDoc.name, path.extname(stepDoc.name));
  const pyCandidates = await ProjectFile.find({
    projectId,
    userId,
    name: new RegExp(`^${base.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\.py$`, 'i'),
  }).sort({ createdAt: -1 }).limit(1);

  let scriptPath = null;
  if (pyCandidates[0]) {
    scriptPath = path.join(workDir, pyCandidates[0].name);
    await pipeline(await getObjectStream(pyCandidates[0].s3Key), createWriteStream(scriptPath));
  } else {
    const anyPy = await ProjectFile.find({
      projectId,
      userId,
      name: /\.py$/i,
      kind: 'other',
    }).sort({ createdAt: -1 }).limit(3);

    for (const doc of anyPy) {
      const local = path.join(workDir, doc.name);
      await pipeline(await getObjectStream(doc.s3Key), createWriteStream(local));
      const text = await fs.readFile(local, 'utf8');
      if (/def\s+gen_dxf\s*\(/i.test(text) && /def\s+gen_step\s*\(/i.test(text)) {
        scriptPath = local;
        break;
      }
    }
  }

  if (!scriptPath) return null;

  const scriptText = await fs.readFile(scriptPath, 'utf8');
  if (!/def\s+gen_dxf\s*\(/i.test(scriptText)) return null;

  onProgress('Exporting DXF for laser cutting (skills/cad/scripts/dxf)…');
  const dxfPath = await exportDxfFromScript({
    workDir,
    scriptName: path.basename(scriptPath),
  });
  const dxfDoc = await uploadSidecarIfExists({
    userId,
    projectId,
    workDir,
    fileName: path.basename(dxfPath),
    onProgress,
  });
  return dxfDoc;
}

export async function executeSendCutSendPreflight({
  userId,
  projectId,
  userMessage,
  onProgress = () => {},
}) {
  const meta = skillMeta('sendcutsend');
  onProgress(`Skill: ${meta.label} — preflight report`);

  const candidates = await ProjectFile.find({
    projectId,
    userId,
    $or: [
      { kind: 'step' },
      { kind: 'dxf' },
      { name: /\.(step|stp|dxf)$/i },
    ],
  }).sort({ createdAt: -1 });

  const target = candidates[0];
  if (!target) {
    return {
      ok: false,
      skill: 'sendcutsend',
      error: 'No STEP/DXF file in project. Generate or import a part first, then ask for SendCutSend preflight.',
    };
  }

  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), 'solidxcad-scs-'));
  const localPath = path.join(workDir, target.name);
  const reportName = `sendcutsend_${path.basename(target.name, path.extname(target.name))}.md`;
  const reportPath = path.join(workDir, reportName);

  try {
    await pipeline(await getObjectStream(target.s3Key), createWriteStream(localPath));
    const stat = await fs.stat(localPath);
    let ext = path.extname(target.name).toLowerCase();
    let dxfDoc = null;

    if (ext !== '.dxf') {
      try {
        dxfDoc = await tryExportDxfForStep({
          userId,
          projectId,
          stepDoc: target,
          workDir,
          onProgress,
        });
        if (dxfDoc) ext = '.dxf';
      } catch (dxfErr) {
        console.warn('[sendcutsend] DXF auto-export:', dxfErr.message);
      }
    }

    const report = [
      '# SendCutSend preflight (automated)',
      '',
      `**Source file:** ${target.name}`,
      `**Size:** ${stat.size} bytes`,
      `**Format:** ${ext === '.dxf' ? 'DXF (2D laser)' : 'STEP (3D — export DXF for flat laser parts)'}`,
      dxfDoc ? `**DXF sidecar:** ${dxfDoc.name}` : '',
      `**User request:** ${userMessage.trim()}`,
      '',
      '## Checklist',
      '1. Confirm material, thickness, and service at https://sendcutsend.com',
      '2. Verify hole sizes, slot widths, and bend lines against SendCutSend specs',
      '3. Upload DXF for flat laser parts; STEP for 3D routing when supported',
      '',
      '## Status',
      `- DXF ready: **${dxfDoc ? 'yes' : 'no'}**${!dxfDoc ? ' — ask chat: "export DXF for laser cutting" with gen_dxf() in CAD script' : ''}`,
      '- File present in project: **yes**',
      '',
      '_Generated by SolidX CAD sendcutsend skill_',
    ].filter(Boolean).join('\n');

    await fs.writeFile(reportPath, report, 'utf8');
    const reportKey = buildS3Key(userId, projectId, `models/${reportName}`);
    const upload = await uploadFile(reportKey, reportPath, 'text/markdown');

    const fileDoc = await ProjectFile.create({
      projectId,
      userId,
      name: reportName,
      s3Key: upload.key,
      mimeType: 'text/markdown',
      kind: 'other',
    });

    onProgress(`Preflight report saved: models/${reportName}`);
    if (dxfDoc) onProgress(`DXF ready: models/${dxfDoc.name}`);
    onProgress('Review report in CAD Viewer — complete material/SKU on sendcutsend.com');

    try {
      const { syncProjectWorkspace } = await import('./projectWorkspace.js');
      await syncProjectWorkspace({ userId, projectId });
    } catch {
      // non-fatal
    }

    return {
      ok: true,
      skill: 'sendcutsend',
      file: fileDoc,
      dxfFile: dxfDoc,
      sourceFile: target.name,
    };
  } catch (err) {
    return { ok: false, skill: 'sendcutsend', error: err.message };
  } finally {
    await fs.rm(workDir, { recursive: true, force: true });
  }
}
